name: Build Windows Desktop

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-windows:

    runs-on: windows-2022

    steps:

      # ==========================================
      # 1. تحميل المشروع
      # ==========================================
      - name: Checkout Code
        uses: actions/checkout@v4


      # ==========================================
      # 2. إعداد Flutter
      # ==========================================
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: stable
          cache: true


      # ==========================================
      # 3. التحقق من Flutter
      # ==========================================
      - name: Flutter Doctor
        run: flutter doctor -v


      # ==========================================
      # 4. تفعيل Windows Desktop
      # ==========================================
      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop


      # ==========================================
      # 5. تنظيف المشروع
      # ==========================================
      - name: Flutter Clean
        run: flutter clean


      # ==========================================
      # 6. تحميل Packages
      # ==========================================
      - name: Flutter Pub Get
        run: flutter pub get


      # ==========================================
      # 7. بناء Windows Release
      # ==========================================
      - name: Build Windows Release
        run: flutter build windows --release


      # ==========================================
      # 8. ضغط ملف البرنامج
      # ==========================================
      - name: Create ZIP
        shell: pwsh
        run: |
          Compress-Archive `
            -Path "build\windows\x64\runner\Release\*" `
            -DestinationPath "AbuShadyTransport-Windows.zip"


      # ==========================================
      # 9. رفع البرنامج كـ Artifact
      # ==========================================
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: AbuShadyTransport-Windows
          path: AbuShadyTransport-Windows.zip
