name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable
          cache: true

      - name: Configure Flutter
        run: flutter config --no-analytics

      - name: Install Android SDK 34
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-34" \
            "build-tools;34.0.0"

      - name: Check Android Configuration
        run: |
          echo "===== app/build.gradle ====="
          cat android/app/build.gradle

      - name: Install Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Generate App Icon
        run: dart run flutter_launcher_icons

      - name: Build APK Release
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Alaa-Accounts-Release-APK
          path: build/app/outputs/flutter-apk/*.apk
