name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Clean
        run: flutter clean

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: alsayed-elnamas-windows
          path: build/windows/x64/runner/Release/
